#!/bin/bash

echo "🐄 MAILCOW INTEGRATION SETUP"
echo "============================="
echo ""
echo "📋 POSTUP PRO MAILCOW SETUP:"
echo ""
echo "1️⃣ INSTALACE MAILCOW:"
echo "   git clone https://github.com/mailcow/mailcow-dockerized"
echo "   cd mailcow-dockerized"
echo "   ./generate_config.sh   # zadej doménu např. mail.doklad.ai"
echo "   nano mailcow.conf      # uprav časové pásmo na Europe/Prague"
echo "   docker compose pull"
echo "   docker compose up -d"
echo ""
echo "2️⃣ KONFIGURACE DNS (na mail.doklad.ai):"
echo "   A     mail.doklad.ai     → IP_VAŠEHO_SERVERU"
echo "   MX    doklad.ai          → mail.doklad.ai"
echo "   TXT   doklad.ai          → v=spf1 mx a ~all"
echo ""
echo "3️⃣ VYTVOŘENÍ EMAIL ÚČTU V MAILCOW:"
echo "   - Otevřít https://mail.doklad.ai (Mailcow Admin)"
echo "   - Přihlásit jako admin"
echo "   - Vytvořit domain: doklad.ai"
echo "   - Vytvořit mailbox: noreply@doklad.ai"
echo ""
echo "4️⃣ SMTP ÚDAJE PRO APLIKACI:"
echo "   Host: mail.doklad.ai"
echo "   Port: 587 (STARTTLS)"
echo "   User: noreply@doklad.ai"
echo "   Pass: heslo_z_mailcow"
echo ""
echo "5️⃣ ENVIRONMENT VARIABLES:"
echo "   SMTP_HOST=mail.doklad.ai"
echo "   SMTP_PORT=587"
echo "   SMTP_USER=noreply@doklad.ai"
echo "   SMTP_PASS=heslo_z_mailcow"
echo ""
echo "🚀 Po dokončení systém automaticky přepne na Mailcow SMTP!"