#!/bin/bash

echo "🔧 DNS Records Setup for Amazon SES Anti-Spam Authentication"
echo "=========================================================="
echo ""

echo "To prevent emails from going to spam, you need to add these DNS records to your doklad.ai domain:"
echo ""

echo "1. 📧 SPF Record (Required)"
echo "   Type: TXT"
echo "   Name: doklad.ai"
echo "   Value: v=spf1 include:amazonses.com ~all"
echo ""

echo "2. 🔐 DKIM Records (Critical for deliverability)"
echo "   ⚠️  First enable DKIM in AWS SES Console:"
echo "   - Go to SES Console → Verified identities → doklad.ai"
echo "   - Click 'DKIM' tab → Enable DKIM signing"
echo "   - Copy the 3 CNAME records provided"
echo "   - Add them to your DNS:"
echo ""
echo "   Type: CNAME"
echo "   Name: [selector1]._domainkey.doklad.ai"
echo "   Value: [provided by AWS]"
echo ""
echo "   Type: CNAME" 
echo "   Name: [selector2]._domainkey.doklad.ai"
echo "   Value: [provided by AWS]"
echo ""
echo "   Type: CNAME"
echo "   Name: [selector3]._domainkey.doklad.ai"
echo "   Value: [provided by AWS]"
echo ""

echo "3. 🛡️  DMARC Record (Prevents spoofing)"
echo "   Type: TXT"
echo "   Name: _dmarc.doklad.ai"
echo "   Value: v=DMARC1; p=quarantine; rua=mailto:dmarc@doklad.ai"
echo ""

echo "4. 📨 Custom MAIL FROM Domain (Optional but recommended)"
echo "   Type: MX"
echo "   Name: mail.doklad.ai"
echo "   Value: 10 feedback-smtp.eu-north-1.amazonses.com"
echo ""
echo "   Type: TXT"
echo "   Name: mail.doklad.ai"
echo "   Value: v=spf1 include:amazonses.com ~all"
echo ""

echo "🎯 After adding these records:"
echo "✅ Emails will have proper authentication"
echo "✅ Gmail will not show 'suspicious' warnings"
echo "✅ Deliverability will significantly improve"
echo "✅ Your domain reputation will be protected"
echo ""

echo "⏱️  DNS propagation takes 24-48 hours"
echo "🔍 Verify with: dig TXT doklad.ai"
echo ""
echo "Next step: Run 'node test-email-authentication.js' after DNS setup"