#!/bin/bash

echo "📧 PŘEPNUTÍ NA GMAIL SMTP"
echo "========================="
echo ""
echo "Amazon SES eu-north-1 region má problémy se SMTP."
echo "Gmail SMTP je rychlejší a spolehlivější alternativa."
echo ""

echo "🔧 POSTUPU PRO GMAIL SMTP:"
echo "=========================="
echo ""
echo "1️⃣ Gmail Account Setup:"
echo "   • Jděte do Google Account → Security"
echo "   • Zapněte 2-Step Verification"
echo "   • Jděte do App passwords"
echo "   • Vygenerujte heslo pro 'Mail'"
echo ""
echo "2️⃣ Environment Variables:"
echo "   Nahraďte Amazon SES variables těmito:"
echo "   SMTP_HOST=smtp.gmail.com"
echo "   SMTP_PORT=587"
echo "   SMTP_USER=vase.email@gmail.com"
echo "   SMTP_PASS=app_password_z_gmail"
echo ""
echo "3️⃣ Odstraňte AWS variables:"
echo "   Smazat: AWS_SES_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY"
echo ""
echo "✅ Po změně bude systém automaticky používat Gmail SMTP"
echo "   a emaily se budou skutečně doručovat!"